# Generated by Django 3.0.1 on 2020-01-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaHora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreComercial', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField(blank=True, default=None, null=True)),
                ('cantidadDisponible', models.IntegerField()),
                ('esMedicamento', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=800)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=200)),
                ('usuario', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('total', models.FloatField(blank=True, default=None, null=True)),
                ('factura', models.CharField(max_length=100)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminSite.cliente')),
                ('idPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminSite.pago')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminSite.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ventaProducto',
            fields=[
                ('idVentaProducto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminSite.producto')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminSite.venta')),
            ],
        ),
    ]
