# Generated by Django 3.0.2 on 2020-01-18 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSite', '0004_auto_20200117_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='idCliente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='AdminSite.cliente'),
        ),
    ]
